/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const ArcadeMachine = (props) => {
    const { nodes, materials } = useGLTF('models/arcadeMachine.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Screen_Glass_0.geometry}
                    material={materials.Glass}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Screen_Screen_0.geometry}
                    material={materials.Screen}
                />
            </group>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.SidePanels_BodyLateral_0.geometry}
                material={materials.BodyLateral}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Body_Body_0.geometry}
                material={materials.Body}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_Speaker_0.geometry}
                material={materials.Speaker}
                position={[0, 146.116, -18.884]}
                rotation={[-1.376, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.RightButtons_Buttons_0.geometry}
                material={materials.Buttons}
                position={[31.343, 94.843, 24.395]}
                rotation={[-1.51, 0, Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.RightStick_Stick_0.geometry}
                material={materials.Stick}
                position={[11.072, 95.41, 19.587]}
                rotation={[-1.499, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.LeftButtons_Buttons_0.geometry}
                material={materials.Buttons}
                position={[-8.029, 94.843, 24.395]}
                rotation={[-1.51, 0, Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.LeftStick_Stick_0.geometry}
                material={materials.Stick}
                position={[-28.3, 95.41, 19.587]}
                rotation={[-1.499, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.LeftUpperButtons_Buttons_0.geometry}
                material={materials.Buttons}
                position={[-8.029, 95.828, 8.013]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.RightUpperButtons_Buttons_0.geometry}
                material={materials.Buttons}
                position={[31.317, 95.828, 8.013]}
                rotation={[-Math.PI / 2, 0, Math.PI / 2]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.CoinPlate_BodyMetal_0.geometry}
                material={materials.BodyMetal}
                position={[0, 56.986, 23.601]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MaintenanceDoor_BodyMetal_0.geometry}
                material={materials.BodyMetal}
                position={[0, 26.352, 23.601]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.FicheiroL_FicheiroBody_0.geometry}
                material={materials.FicheiroBody}
                position={[-5, 64.306, 25.221]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.FicheiroR_FicheiroBody_0.geometry}
                material={materials.FicheiroBody}
                position={[5, 64.306, 25.221]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.LowerBody_Body_0.geometry}
                material={materials.Body}
                position={[0, 0.428, -12.294]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.FanSupport_Fan_0.geometry}
                material={materials.material}
                position={[-8.407, 16.578, -47.206]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Fan_Fan_0.geometry}
                material={materials.material}
                position={[-8.407, 16.578, -47.206]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.honeycomb_BodyMetal_0.geometry}
                material={materials.BodyMetal}
                position={[-8.407, 16.578, -48.41]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.FanCase_Fan_0.geometry}
                material={materials.material}
                position={[-8.407, 16.578, -47.206]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.BackMaintenanceDoor_BodyMetal_0.geometry}
                material={materials.BodyMetal}
                position={[17.02, 30.933, -48.636]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.MaintenanceDoor001_KeyLockMetal_0.geometry}
                material={materials.KeyLockMetal}
                position={[0, 26.352, 23.601]}
                scale={100}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube_Fan_0.geometry}
                material={materials.material}
                position={[-8.407, 16.578, -47.206]}
                rotation={[-Math.PI / 2, 0, 0]}
                scale={100}
            />
        </group>
    )
}

useGLTF.preload('models/arcadeMachine.glb')

export default ArcadeMachine;

